### ISSUE TITLE
Make sure Discord has a CoC on it

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#12]
We might already have this, put it in place if not.

e.g.:

![unknown](https://user-images.githubusercontent.com/134455/104218193-62449500-540a-11eb-834c-27072d5d3f58.png)

**Comment by chadwhitacre** [comment]
Found it. It's called "[Rules Screening](https://support.discord.com/hc/en-us/articles/1500000466882-Rules-Screening-FAQ)."

**Comment by chadwhitacre** [comment]
Done. Made up this description, can tweak if need be:

> This is the official Discord community for Sentry, your favorite application performance and error monitoring software. Welcome! 👋

New user flow:

<img width="1286" alt="Screen Shot 2021-02-23 at 5 34 31 PM" src="https://user-images.githubusercontent.com/134455/108917270-7a105b00-75fd-11eb-9a68-f36c2b1971b4.png">

<img width="1286" alt="Screen Shot 2021-02-23 at 5 34 34 PM" src="https://user-images.githubusercontent.com/134455/108917265-7977c480-75fd-11eb-9587-2bc5b24e88f4.png">

<img width="1286" alt="Screen Shot 2021-02-23 at 5 34 49 PM" src="https://user-images.githubusercontent.com/134455/108917262-78df2e00-75fd-11eb-9b00-cf215d2c07cb.png">

<img width="1286" alt="Screen Shot 2021-02-23 at 5 34 53 PM" src="https://user-images.githubusercontent.com/134455/108917264-7977c480-75fd-11eb-9c20-af334705959f.png">

**Comment by BYK** [comment]
@chadwhitacre what's holding us from closing this issue now?

**Comment by chadwhitacre** [comment]
Nothing! 😁
