### ISSUE TITLE
template enforcer is confused

### ISSUE THREAD

**Issue by frame** [getsentry/.github#23]
https://github.com/getsentry/onpremise/issues/837

Hi. I did use the template but added an additional headline. This or something else might have tripped the parser. I added "Feature Request: " to the title after the fact, wasn't sure if it was needed.

Thanks for taking a look!

**Comment by BYK** [comment]
Duplicate of #15.

Hey @frame thanks for reporting and sorry for the inconvenience. We're working on this :)
