### ISSUE TITLE
Adapt bots to SSO

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#27]
We just turned on [SSO for our GitHub org](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-identity-and-access-management-with-saml-single-sign-on), need to audit bots and make sure they still work.

**Comment by BYK** [comment]
https://docs.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on

This needs to be done after we create _real_ Google accounts for our bots: getsentry-bot and getsentry-release.

We can keep their old emails and use the _real_ accounts only for verification purposes.

**Comment by chadwhitacre** [comment]
Document here: https://www.notion.so/sentry/GitHub-14847f935cd14b6596b1f750786deffa#e2584c4bf2b349219c761b7e9b319e2f

**Comment by BYK** [comment]
This was done ad-hoc with myself and @dcramer.
