### ISSUE TITLE
Test suite occasionally fails with issue number mismatch

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#30]
### Environment

GHA test suite (run manually atm).

### Steps to Reproduce

1. Run test suite for validating new issues in GHA.

### Expected Result

Test suite is consistently green.

### Actual Result

Test suite is occasionally red with an error like this:

```
download-and-extract backed right off the edge!
```

and a mismatch in the expected and actual issue number in the downloaded log file.

### Notes

We make an assumption that `run_number` == `issue_number - 1` (offset vs. ordinal), which holds _most_ of the time. We make this assumption because there doesn't seem to be a way to request the logs for a workflow run based directly on the issue number for the issue event that triggered the run, and it's going to be less download-y to start with `run_number` and radiate outwards in the list of all recent workflow runs than some other strategy (such as always starting with the most recent run and working backwards). The way I see to resolve this bug is to implement the radiating outwards. ☺️ But! I'm open to other solutions ... best would be a way to determine with certainty from the list of runs which run is the one we want.

**Comment by chadwhitacre** [comment]
<img width="580" alt="Screen Shot 2021-01-29 at 11 33 00 AM" src="https://user-images.githubusercontent.com/134455/106301475-c4343580-6225-11eb-8e31-5144de65639f.png">

**Comment by BYK** [comment]
Asked publicly to GitHub, now it's their turn: https://github.community/t/api-to-get-workflow-run-associated-with-an-issue/158405

**Comment by chadwhitacre** [comment]
Gets worse as the test case count goes up (makes sense). Using `max-parallel` to limit the damage for now.

**Comment by chadwhitacre** [comment]
This is fixed. If/when we care we can improve log downloading to allow for parallelizing the tests.
