### ISSUE TITLE
template enforcer is confused

### ISSUE THREAD

**Issue by dg-eparizzi** [getsentry/.github#39]
https://github.com/getsentry/sentry/issues/23681

**Comment by BYK** [comment]
@dg-eparizzi no it is not, you are not using any of the provided issue templates there.

**Comment by dg-eparizzi** [comment]
> @dg-eparizzi no it is not, you are not using any of the provided issue templates there.

Well, it's the template that the "Report Issue" link from the Azure DevOps integration generates...

![mrl2Jv5QR7](https://user-images.githubusercontent.com/72451869/107232253-7f787d80-6a21-11eb-9601-d9a0e4144a2f.gif)

**Comment by BYK** [comment]
@dg-eparizzi thanks for the heads up on this. Will fix the link!
