### ISSUE TITLE
template enforcer is confused

### ISSUE THREAD

**Issue by tomyam1** [getsentry/.github#43]
https://github.com/getsentry/sentry-docs/issues/3093

**Comment by BYK** [comment]
@tomyam1 why do you think the bot is confused as you don't seem to have used the template there: https://github.com/getsentry/sentry-docs/issues/new?assignees=&labels=&template=issue.md

(the main headings don't match)

**Comment by tomyam1** [comment]
I think the only difference  is that I didn't include the optional `Possible Solution` section:

![image](https://user-images.githubusercontent.com/3265649/107963630-18267480-6fb1-11eb-8440-5fb30a56c12d.png)

**Comment by chadwhitacre** [comment]
Yes, that's it @tomyam1. Sorry for the trouble, should be addressed now via https://github.com/getsentry/sentry/pull/23878.

Looks like you're back on track with https://github.com/getsentry/sentry-docs/issues/3094, yes?

**Comment by tomyam1** [comment]
> Yes, that's it @tomyam1. Sorry for the trouble, should be addressed now via [getsentry/sentry#23878](https://github.com/getsentry/sentry/pull/23878).

Super. Thanks

> Looks like you're back on track with [getsentry/sentry-docs#3094](https://github.com/getsentry/sentry-docs/issues/3094), yes?

Indeed

**Comment by chadwhitacre** [comment]
Thanks for helping us [improve our docs and] train our bot! 😬
