### ISSUE TITLE
Apply a `Status: Unrouted` label to all issues that pass validation

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#44]
### Problem

The Open Source Team is responsible for routing all incoming issues to the appropriate team, but we don't have a good queue to work against, which makes it hard to ensure that we're not missing issues. The general GitHub notification stream is waaaaay too noisy (regardless of how it's consumed: email, web, etc.).

### Solution

Teach the `validate-new-issue` action to apply a `Status: Unrouted` label to issues that pass validation. With this label humans (for now) can use a search like this to stay on top of routing:

https://github.com/search?q=org%3Agetsentry+label%3A%22Status%3A+Unrouted%22+state%3Aopen&type=Issues

**Comment by BYK** [comment]
Why not https://github.com/search?q=org%3Agetsentry+no%3Alabel+state%3Aopen+is%3Aissue&type=issues as we already close invalid issues automatically?

**Comment by chadwhitacre** [comment]
Because that doesn't distinguish between issues that were authored by Sentry employees and those from outside. We care primarily about those coming from outside.

**Comment by BYK** [comment]
Hmm, good point. That said issues from Sentry employees still need to be routed and they are still subject to stalebot, right? Not sure if distinguishing them from external is a great idea.

**Comment by chadwhitacre** [comment]
I think for employees routing and triage is on them. The purpose of stalebot is precisely to incentivize employees to (route and) triage issues. No?

**Comment by BYK** [comment]
Fair argument, I'm 👍🏻 for adding this new label then.
