### ISSUE TITLE
Issue templates with no headers are a lie

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#47]
### Environment

GitHub Actions

### Steps to Reproduce

1. Set up a repo with an issue template with no headers.
2. As a non-org-member, create a new issue with no headers in that repo.

### Expected Result

Issue is allowed, since there is a template with no headers.

### Actual Result

Issue is not allowed.

**Comment by BYK** [comment]
Couldn't this be intentional? 😀

**Comment by chadwhitacre** [comment]
It'd be a confusing intention. Contributor experience:

1. Click "New Issue."
2. Pick template. Happens to have no headers.
3. Fill out template.
4. Issue rejected for not matching any _other_ template. 😞

I noticed this because our default feature request template [currently has no headers](https://github.com/getsentry/.github/blob/f663e1dd631880fa51cba2126f6192c92826c437/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md). The three repos where the validation bot is actually deployed override the default, which is why we haven't noticed in practice yet. We need to aware of this issue and resolve it one or another before deploying the bot to additional repos.

**Comment by BYK** [comment]
Oh wait sorry, I agree with you. I misread the issue :)

**Comment by BYK** [comment]
This was fixed with #29.
