### ISSUE TITLE
Notify in Slack on route

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#55]
When we route a ticket, find a way to send a Slack message.

**Comment by BYK** [comment]
@mitsuhiko did `/github subscribe getsentry/publish` the other day. Let's see how that works and use that?

**Comment by chadwhitacre** [comment]
I believe @manuzope already has that, the idea here is to scope down to just a team's assignments vs. the whole org.

**Comment by BYK** [comment]
@chadwhitacre yup, makes sense. We may want to start working on that app then :D

**Comment by chadwhitacre** [comment]
+1 from @jeremybourque

**Comment by chadwhitacre** [comment]
+1 from @scefali

**Comment by chadwhitacre** [comment]
@logicalbomb points out that SentaurBot already has Slack/GitHub username mapping

cf. Sentry's own alerts for ideas on team vs. individual
