### ISSUE TITLE
Add a welcome message for valid issues

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#58]
For invalid issues we comment, but for valid issues we do nothing. Let's add a welcome message that gives us a chance to:

- link to the [processing process](https://develop.sentry.dev/processing-tickets/) and emphasize the SLAs
- nudge paying customers towards support
- ...?

----------

_Reticketed from https://github.com/getsentry/open.sentry.io/issues/1._

**Comment by chadwhitacre** [comment]
cf. https://github.com/github/docs/pull/3769#issuecomment-781374755

**Comment by BYK** [comment]
As stated earlier, I'm not a fan of this but will leave closing or putting to backlog to @chadwhitacre.

**Comment by chadwhitacre** [comment]
> I'm not a fan of this

Stated where? All I see is a 👍 from you on the description. 😂

**Comment by BYK** [comment]
Lol, sorry. I think this was a Slack conversation. I don't think automated welcome messages are valuable as they are not coming from a real human?

**Comment by chadwhitacre** [comment]
Letting go of this, we can reticket in eng-pipes if the use cases arises again.
