### ISSUE TITLE
Chill out, stalebot!

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#6]
@bruno-garcia:

> 4 weeks is nothing
> I'd go with 6 months :D

@benvinegar:

> 4 weeks seems aggressive - is that typical for a project like this?
> I was thinking a few months
> Eg it tagged a ticket of mine that was 2 years old - that makes sense

**Comment by chadwhitacre** [comment]
The thinking behind tuning to 4 weeks is to incentivize triage. If someone cares enough about a ticket they should apply the `Status: Accepted` label. This gives us a record of who wants to "champion" the ticket, so to speak.

**Comment by bruno-garcia** [comment]
There are perhaps two use cases:

1. Repositories where the issue tracker isn't triaged.
2. Actively triaged repositories.

Stale bot is useful in both cases, and I see it working with marking `Status: Accepted` as you described on the first use case.

In the case of `2`, which is the SDKs of the mobile team for example (10 repos), all issues are replied to within days (usually 1 or 2). We often tag (`enhancement`,`bug`) to all issues and close issues when the resolution is clear. But obviously issues keep growing faster than we can handle them. In this case, an issue that's say, 6 months old, or 1 year old, without any activity. That's really stale, and could be closed. This way we don't have to add `Status: Accepted` to every single issue we receive. The bot will just clean up old issues and, the assumption is that rarely they'll be reopen anyway. If they are reopen, they just got another 6 months (or N) to live.

**Comment by BYK** [comment]
6 months is too long. I'd say we should re-evaluate all stale issues every quarter and prune them aggressively. So the longest I'd go is something less than 3 months. Maybe 10 weeks tops.

**Comment by chadwhitacre** [comment]
> Stale bot is useful in both cases
> This way we don't have to add `Status: Accepted` to every single issue we receive.

@bruno-garcia What I hear you saying is that triaging repos is a good thing ... aaaaand your team already has an established process for this.

From our DM:

> can we use a custom tag?
> I mean, if I have any tags it's been triaged

Were in luck! The action _does_ accept multiple values for `exempt-issue-labels`. If we include additional labels would that avoid stalebot adding friction to your workflow?

**Comment by bruno-garcia** [comment]
awesome! thanks 👍

**Comment by chadwhitacre** [comment]
Cool. Noted on https://github.com/getsentry/.github/issues/10. 👍

**Comment by chadwhitacre** [comment]
Folks seem to have accepted stalebot's current pace. Closing.
