### ISSUE TITLE
Surface GitHub issue traction into Jira

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#60]
Would be great when looking at a Jira ticket that has a public GitHub shadow ticket, to see the GitHub engagement level (comments, reactions) at a glance in Jira (sidebar?).

**Comment by chadwhitacre** [comment]
Explore Unito here

**Comment by BYK** [comment]
Sent to backlog but not sure if this is still worthwhile.

**Comment by chadwhitacre** [comment]
Yeah it seems we've drifted away from this idea of shadow tickets, we can reopen if we drift back.
