### ISSUE TITLE
Don't route if already routed

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#68]
If there's already a `Status: *` label on an issue then the `Team: *` action should not re-route.

E.g.

https://github.com/getsentry/sentry/issues/26121

<img width="906" alt="Screen Shot 2021-05-18 at 5 19 18 PM" src="https://user-images.githubusercontent.com/134455/118724957-4d836e00-b7fd-11eb-8c9c-8847a8d15d14.png">

**Comment by BYK** [comment]
I disagree as the action is ambiguous. We should refine this to say if there is either `Status: Backlog` or `Status: In Progress` label, _then_ we should not touch them. Otherwise (for untriaged, unrouted, needs more information etc.) marking as needs triage makes sense.

WDYT @chadwhitacre?

**Comment by PeloWriter** [comment]
Agreeing with @BYK. If the `Status` is empty, then labeling it as `Untriaged` makes sense. But if the issue already has a `Status` set to `In Progress` or `Backlog`, then it's unhelpful to re-set it to `Untriaged`.
