### ISSUE TITLE
Remove `Status: Stale` when `Status: Accepted` is applied

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/.github#7]
This would make queries cleaner.

**Comment by chadwhitacre** [comment]
Skim of first 15 issues looks like some/most folks are manually removing stale when accepting.

Two implementation options:

1. Simple action that we own, probably enough to run daily.
2. Upstream in https://github.com/actions/stale/issues/136.

**Comment by chadwhitacre** [comment]
Or just unapply Stale manually at query time.

**Comment by chadwhitacre** [comment]
Done upstream in https://github.com/actions/stale/pull/268. Need to bump our version pin.

**Comment by BYK** [comment]
This is done via #65 and #67.
